sudo: false
language: node_js
node_js: 10
cache: yarn
script:
  - npm run build
before_deploy:
  - cd ./dist
deploy:
  skip_cleanup: true
  provider: npm
  email: felix@stkn.org
  tag: six
  api_key:
    secure: IOIv+xrg6+kC02dLC8JRRHJ14ueZM3zA8mK5hcdso5aR6HTI/ugioy1rMCe3nqV0N9X/tzEZkLtNTm2hw0GHkODmQxLJ1rXYfHSVkKGDCQpOtQV3HPBcp4VR8doMbF3aTrYI3yC0mo0UkSvwEw7IRHIeXx01KHMJVmbR3rJaNrInTxgdvOgFg7VzGHgmpsfxjKLhgmARWNyWitu3+y/3i+ESZr0L0qSAWsP+23ZqJf7YMFEau4OVncB1Z6wdR3fthtMNp92CSiPEI8yyb5kZyNmDff9vB5vrdQ+3AM4gMXGskX+yiS8xeMjswMFDJvgzfQyQ1Tjj0UkxRSiOS0tnaAmNNIi/UYR/6EB66yQKI4GnN9gSHoVEM4XXyQ/4X/5toAs3q77nVswjdYRZGf1S52nSFOIr/02W7gZabZKK8s9sEyy3tBjeKi/uaGBCDWKQ7Ykmi2xYXb17eLspysKgeEMg4ll12QZiGi8R6NP3nOhcPl9RMGTOow8M9ZlsPVsPKib8gi+ukusScPAnFuWZQcafsIJ4JMizSGJlT/OPV1O2uOnOGh7d2wLwNyG/A59dqB/YlW12h4uSM73b6JVpdUFC4iE2SiWfhyHwHp0yPif3UmBDfYUhuYQpapbQP+6mjE69NLgG98erf/bbwdsfnoFbO0ag1qG/DubJnNw4i9I=
  on:
    tags: true
    repo: cebor/angular-highcharts
